### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by woss** [devcontainers-contrib/features#426]
### Feature id and version

ghcr.io/devcontainers-contrib/features/pnpm:2

### Devcontainer base Image

mcr.microsoft.com/devcontainers/typescript-node:18-bullseye

### What happened?

The following setting does not install the correct version. it is always latest.

```
"ghcr.io/devcontainers-contrib/features/pnpm:2": {
      "version": "7.26.3"
    },
```

### Relevant log output

```shell
in the container run `pnpm --version` i get `8.3.1` instead of `7.26.3`
```

**Comment by danielbraun89** [comment]
@woss thanks for reporting! 
Oddly enough this looks to be the same bug as #267 (version value is being leaked into the npm installation script)
In the PR for this issue indeed it seems pnpm was skipped and did not got updated like the rest of the features.  will release a PR soon that will fix this

**Comment by danielbraun89** [comment]
Fixed in `ghcr.io/devcontainers-contrib/features/pnpm:2.0.2` :)

**Comment by woss** [comment]
@danielbraun89 Thanks for the message but i am still facing the same problem,

this output is inside the `postCreateCommand` 
![image](https://github.com/devcontainers-contrib/features/assets/80440/81f3e373-b4d3-4421-a424-24c18e358ec4)

```jsonc
    // https://github.com/devcontainers-contrib/features/issues/426
    "ghcr.io/devcontainers-contrib/features/pnpm:2.0.2": {
      "version": "7.32.4"
    },
```

**Comment by danielbraun89** [comment]
I did the mistake of testing with debian image and missed that the bug reproducing on `mcr.microsoft.com/devcontainers/typescript-node:18-bullseye`.
I now see this is a result of the image already containing `pnpm` and in this case the installation is getting purposely skipped, regardless of version. Which is of course a bug. A bug which is not even pnpm related but affecting any npm-based feature with the same circumstances.
I have prepared a new `npm-package` fix that will also check for equality of version before skipping the installation,  
and rereleased the pnpm feature - along all other npm based features.

Also have added test specifically for `pnpm` to test your combination of image + version scenario (https://github.com/devcontainers-contrib/features/pull/434/files#diff-70608a049d18cd0836335af045f67c3d01aee892a7b0626c0ae3c49db29e1d98)

try:  `ghcr.io/devcontainers-contrib/features/pnpm:2.0.3`

**Comment by woss** [comment]
I did a full (no-cache) rebuild and it is working. It is tested locally and in codespaces.

Thank you for the effort and quick fix :) 


![image](https://github.com/devcontainers-contrib/features/assets/80440/85baf4ca-9257-469a-9805-bacb63b5f665)
```jsonc
 // https://github.com/devcontainers-contrib/features/issues/426
    "ghcr.io/devcontainers-contrib/features/pnpm:2.0.3": {
      "version": "7.32.4"
    },
```
